/**
 * URL serialisation for Quiet Dynamics configuration.
 *
 * A URL identifies the active simulation and its seed. Values that differ
 * from the configuration generated by that seed are stored as explicit
 * overrides.
 *
 * Transient state such as `paused` is deliberately excluded.
 */

import type {
  PaletteName,
  VisualSettings,
  PlaybackSettings,
} from "../types/settings";

import type { SimulationName } from "../types/simulationName";

export type { SimulationName } from "../types/simulationName";

const MAX_UINT32 = 0xffffffff;

export interface SharedUrlSettings extends VisualSettings, PlaybackSettings {}

export interface SharedUrlDefaults {
  visual: VisualSettings;
  playback: PlaybackSettings;
}

export interface SimulationUrlState<TSettings> {
  simulation: SimulationName;
  seed: number;
  settings: TSettings;
  shared: SharedUrlSettings;
}

export interface UrlCodec<TSettings> {
  simulation: SimulationName;
  defaults: TSettings;
  createRandomConfig: (seed: number) => TSettings;
  applyOverrides: (settings: TSettings, params: URLSearchParams) => TSettings;
  serializeOverrides: (
    settings: TSettings,
    base: TSettings,
    params: URLSearchParams,
  ) => void;
}

type SHARED_KEYS = [
  "background",
  "palette",
  "trailLifetime",
  "glow",
  "rainbowSpeed",
  "simulationSpeed",
];

type SharedKey = SHARED_KEYS[number];

function parseSeed(value: string | null): number | null {
  if (value === null) {
    return null;
  }

  const seed = Number(value);

  if (!Number.isInteger(seed) || seed < 0 || seed > MAX_UINT32) {
    return null;
  }

  return seed;
}

function parseNumber(
  value: string | null,
  minimum: number,
  maximum: number,
): number | null {
  if (value === null) {
    return null;
  }

  const parsed = Number(value);

  if (!Number.isFinite(parsed) || parsed < minimum || parsed > maximum) {
    return null;
  }

  return parsed;
}

function parseBackground(value: string | null): string | null {
  if (value === null || !/^#[0-9a-fA-F]{6}$/.test(value)) {
    return null;
  }

  return value.toLowerCase();
}

function parsePalette(value: string | null): PaletteName | null {
  switch (value) {
    case "neon-rainbow":
    case "rainbow":
    case "gradient":
    case "solid":
      return value;

    default:
      return null;
  }
}

function applySharedOverrides(
  defaults: SharedUrlSettings,
  params: URLSearchParams,
): SharedUrlSettings {
  const sharedBase: SharedUrlSettings = {
    ...defaults,
    paused: false,
  };

  const background = parseBackground(params.get("background"));

  if (background !== null) {
    sharedBase.background = background;
  }

  const palette = parsePalette(params.get("palette"));

  if (palette !== null) {
    sharedBase.palette = palette;
  }

  const trailLifetime = parseNumber(params.get("trailLifetime"), 2, 40);

  if (trailLifetime !== null) {
    sharedBase.trailLifetime = trailLifetime;
  }

  const glow = parseNumber(params.get("glow"), 0, 200);

  if (glow !== null) {
    sharedBase.glow = glow;
  }

  const rainbowSpeed = parseNumber(params.get("rainbowSpeed"), 0, 3);

  if (rainbowSpeed !== null) {
    sharedBase.rainbowSpeed = rainbowSpeed;
  }

  const simulationSpeed = parseNumber(params.get("simulationSpeed"), 0.1, 2.5);

  if (simulationSpeed !== null) {
    sharedBase.simulationSpeed = simulationSpeed;
  }

  return sharedBase;
}

function serializeSharedOverrides(
  current: SharedUrlSettings,
  base: SharedUrlSettings,
  params: URLSearchParams,
): void {
  const values: Record<SharedKey, string> = {
    background: current.background,
    palette: current.palette,
    trailLifetime: String(current.trailLifetime),
    glow: String(current.glow),
    rainbowSpeed: String(current.rainbowSpeed),
    simulationSpeed: String(current.simulationSpeed),
  };

  if (current.background !== base.background) {
    params.set("background", values.background);
  }

  if (current.palette !== base.palette) {
    params.set("palette", values.palette);
  }

  if (current.trailLifetime !== base.trailLifetime) {
    params.set("trailLifetime", values.trailLifetime);
  }

  if (current.glow !== base.glow) {
    params.set("glow", values.glow);
  }

  if (current.rainbowSpeed !== base.rainbowSpeed) {
    params.set("rainbowSpeed", values.rainbowSpeed);
  }

  if (current.simulationSpeed !== base.simulationSpeed) {
    params.set("simulationSpeed", values.simulationSpeed);
  }
}

/**
 * Load a simulation configuration and shared settings from the current URL.
 *
 * If the URL does not identify a valid simulation, the supplied default
 * simulation is used.
 */
export function loadSimulationFromUrl<TSettings>(
  codec: UrlCodec<TSettings>,
  defaults: SharedUrlDefaults,
): SimulationUrlState<TSettings> {
  const params = new URLSearchParams(window.location.search);

  const parsedSeed = parseSeed(params.get("seed"));
  const seed = parsedSeed ?? 0;

  const simulationBase =
    seed === 0 ? { ...codec.defaults } : codec.createRandomConfig(seed);

  const settings = codec.applyOverrides(simulationBase, params);

  const sharedDefaults: SharedUrlSettings = {
    ...defaults.visual,
    ...defaults.playback,
  };

  const shared = applySharedOverrides(sharedDefaults, params);

  return {
    simulation: codec.simulation,
    seed,
    settings,
    shared,
  };
}

function assertMatchingSimulation<TSettings>(
  state: SimulationUrlState<TSettings>,
  codec: UrlCodec<TSettings>,
): void {
  if (state.simulation !== codec.simulation) {
    throw new Error(
      `Simulation state "${state.simulation}" does not match URL codec "${codec.simulation}".`,
    );
  }
}

/**
 * Serialise a complete simulation configuration into the current URL.
 */
export function setSimulationInUrl<TSettings>(
  state: SimulationUrlState<TSettings>,
  codec: UrlCodec<TSettings>,
  defaults: SharedUrlDefaults,
  mode: "replace" | "push" = "replace",
): void {
  assertMatchingSimulation(state, codec);
  const url = new URL(window.location.href);

  url.search = "";

  if (state.seed !== 0) {
    url.searchParams.set("seed", String(state.seed));
  }

  const simulationBase =
    state.seed === 0
      ? { ...codec.defaults }
      : codec.createRandomConfig(state.seed);

  const sharedBase: SharedUrlSettings = {
    ...defaults.visual,
    ...defaults.playback,
  };

  serializeSharedOverrides(state.shared, sharedBase, url.searchParams);

  codec.serializeOverrides(state.settings, simulationBase, url.searchParams);

  if (mode === "push") {
    window.history.pushState({}, "", url);
  } else {
    window.history.replaceState({}, "", url);
  }
}
/**
 * Generate a shareable URL without modifying browser history.
 */
export function getSimulationShareUrl<TSettings>(
  state: SimulationUrlState<TSettings>,
  codec: UrlCodec<TSettings>,
  defaults: SharedUrlDefaults,
): string {
  assertMatchingSimulation(state, codec);
  const url = new URL(window.location.href);

  url.search = "";

  if (state.seed !== 0) {
    url.searchParams.set("seed", String(state.seed));
  }

  const simulationBase =
    state.seed === 0
      ? { ...codec.defaults }
      : codec.createRandomConfig(state.seed);

  const sharedBase: SharedUrlSettings = {
    ...defaults.visual,
    ...defaults.playback,
  };

  serializeSharedOverrides(state.shared, sharedBase, url.searchParams);

  codec.serializeOverrides(state.settings, simulationBase, url.searchParams);

  return url.toString();
}
